### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by miguelft96** [quadbiolab/VoxHunt#5]
Hi,

I have ran into some issues installing VoxHunt. It seems there is a problem with the Description file. Or am I doing something wrong?

```
devtools::install_github('quadbiolab/voxhunt')
Downloading GitHub repo quadbiolab/voxhunt@HEAD
✓  checking for file ‘/private/var/folders/4h/h11_g5pj4hz53jwk_gklsky00000gn/T/Rtmp24OLDH/remotes2e4683cbc03/quadbiolab-VoxHunt-b0a9262/DESCRIPTION’ ...
─  preparing ‘voxhunt’:
E  checking DESCRIPTION meta-information ...
   Authors@R field gives no person with maintainer role, valid email
   address and non-empty name.
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
Error: Failed to install 'voxhunt' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/private/var/folders/4h/h11_g5pj4hz53jwk_gklsky00000gn/T/Rtmp24OLDH/remotes2e4683cbc03/quadbiolab-VoxHunt-b0a9262/DESCRIPTION’ ... OK
E> * preparing ‘voxhunt’:
E> * checking DESCRIPTION meta-information ... ERROR
E> Authors@R field gives no person with maintainer role, valid email
E> address and non-empty name.
E> 
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.
E> 
```

Here's my session info, by the way.

```
sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] pt_PT.UTF-8/pt_PT.UTF-8/pt_PT.UTF-8/C/pt_PT.UTF-8/pt_PT.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    usethis_2.0.0     devtools_2.3.2    pkgload_1.1.0     R6_2.5.0         
 [7] rlang_0.4.9       fansi_0.4.1       tools_3.6.3       pkgbuild_1.2.0    sessioninfo_1.1.1 cli_2.2.0        
[13] withr_2.3.0       ellipsis_0.3.1    remotes_2.2.0     assertthat_0.2.1  digest_0.6.27     rprojroot_2.0.2  
[19] lifecycle_0.2.0   crayon_1.3.4      processx_3.4.5    purrr_0.3.4       callr_3.5.1       fs_1.5.0         
[25] ps_1.5.0          curl_4.3          testthat_3.0.1    memoise_1.1.0     glue_1.4.2        compiler_3.6.3   
[31] desc_1.2.0        prettyunits_1.1.1
```

When I updated R to version 4.0.3 I get this error:

```
devtools::install_github('quadbiolab/voxhunt')
Downloading GitHub repo quadbiolab/voxhunt@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/quadbiolab/voxhunt/tarball/HEAD' failed
```

Any idea what's causing this?
Thank you

**Comment by joschif** [comment]
Hi miguelft96, 
there seems to have been a problem with the DESCRIPTION file in the most recent version. I just pushed a new version with the fix, should work better now. Let me know how it goes.
Best,
Jonas

**Comment by joschif** [comment]
Also, I have not tested the package in R version 4.0 yet, so I would recommend installing in 3.6. I'll update the package to 4.0 as soon as possible.

**Comment by miguelft96** [comment]
Hey Jonas,
It works perfectly on R 3.6.3 now. Thank you very much! For R 4.0.3 I still get an error message, unfortunately.
Thank you for your help and for developing such a nice package!!
Best,
Miguel

**Comment by quadbiolab** [comment]
Hi Miguel,
In case you are interested, I just pushed a new version of VoxHunt (0.9.0), which should work with R 4.0.3. I'll continue working on it in the next couple of days but feel free to try it. I'll close this for now.
Best,
Jonas

**Comment by RhalenaThomas** [comment]
Hello,
I'd really like to try out VoxHunt on my scRNAseq from organoids.  But I'm having the same install problem as Miguel.  I am using R version 4.1.0 

Here is my error:

> devtools::install_github('quadbiolab/voxhunt')
Downloading GitHub repo quadbiolab/voxhunt@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/quadbiolab/voxhunt/tarball/HEAD' failed


Here is the session info:
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
  [1] Seurat_4.0.0         Rtsne_0.15           colorspace_2.0-0     deldir_0.2-10       
  [5] ellipsis_0.3.2       ggridges_0.5.3       rprojroot_2.0.2      fs_1.5.0            
  [9] rstudioapi_0.13      spatstat.data_2.0-0  leiden_0.3.7         listenv_0.8.0       
 [13] remotes_2.2.0        ggrepel_0.9.1        fansi_0.4.2          codetools_0.2-18    
 [17] splines_4.1.0        cachem_1.0.4         knitr_1.31           polyclip_1.10-0     
 [21] pkgload_1.1.0        jsonlite_1.7.2       ica_1.0-2            cluster_2.1.1       
 [25] png_0.1-7            uwot_0.1.10          shiny_1.6.0          sctransform_0.3.2   

Thank you for any help you can provide.

**Comment by joschif** [comment]
Hi @RhalenaThomas, from your message it's a bit hard for me to tell why exactly the download failed. You can also try to clone the repo with `git clone https://github.com/quadbiolab/VoxHunt.git` and then install from the local directory with `devtools::install_local()`.
